# Generated by Django 2.1.1 on 2018-09-25 16:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=127, verbose_name='title')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
            ],
            options={
                'verbose_name_plural': 'Courses',
                'ordering': ['title'],
                'verbose_name': 'Course',
            },
        ),
        migrations.CreateModel(
            name='EducationGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='education.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('start', models.DateTimeField(verbose_name='Start')),
                ('finish', models.DateTimeField(verbose_name='finish')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='education.Course')),
                ('groups', models.ManyToManyField(to='education.EducationGroup')),
            ],
            options={
                'verbose_name_plural': 'Lecture',
                'ordering': ['title'],
                'verbose_name': 'Lecture',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=200, verbose_name='Last name')),
                ('first_name', models.CharField(max_length=200, verbose_name='First name')),
                ('birth_date', models.DateField(verbose_name='Birth date')),
                ('active', models.BooleanField(default=True, verbose_name='Status')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Students',
                'ordering': ['last_name'],
                'verbose_name': 'Student',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=255, verbose_name='Last name')),
                ('first_name', models.CharField(max_length=255, verbose_name='First name')),
                ('birth_date', models.DateField(verbose_name='Birth date')),
                ('active', models.BooleanField(default=True, verbose_name='Status')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Teachers',
                'ordering': ['last_name'],
                'verbose_name': 'Teacher',
            },
        ),
        migrations.AddField(
            model_name='lecture',
            name='teachers',
            field=models.ManyToManyField(to='education.Teacher'),
        ),
        migrations.AddField(
            model_name='educationgroup',
            name='users',
            field=models.ManyToManyField(db_index=True, to='education.Student'),
        ),
    ]
