# Generated by Django 2.1.1 on 2018-09-26 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='educationgroup',
            old_name='users',
            new_name='students',
        ),
    ]
