# Generated by Django 2.1.1 on 2018-09-26 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0002_auto_20180926_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationgroup',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Status'),
        ),
    ]
