# Generated by Django 2.1.1 on 2018-09-26 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0003_educationgroup_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Status'),
        ),
    ]
