# Generated by Django 2.0.7 on 2018-09-27 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0005_auto_20180927_1041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='educationgroup',
            name='students',
        ),
        migrations.AddField(
            model_name='student',
            name='education_groups',
            field=models.ManyToManyField(blank=True, to='education.EducationGroup', verbose_name='Education Groups'),
        ),
    ]
