# Generated by Django 2.0.7 on 2018-09-27 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0006_auto_20180927_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='groups',
            field=models.ManyToManyField(to='education.EducationGroup', verbose_name='Education Groups'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='teachers',
            field=models.ManyToManyField(to='education.Teacher', verbose_name='Teachers'),
        ),
    ]
